# Generated by Django 5.0.6 on 2024-06-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='exam_name',
            field=models.CharField(default='Default Exam', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('exam_name', 'exam_date')},
        ),
    ]
